# Generated by Django 2.2.4 on 2019-08-13 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedExamtList',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.TextField(verbose_name='Пациент')),
                ('purpose_medical_examination', models.CharField(max_length=20, verbose_name='Цель медосмотра')),
                ('date_medical_examination', models.DateField(verbose_name='Дата медосмотра')),
                ('dat_end', models.DateField(verbose_name='Дата окончанмя действия справки')),
                ('patient_status', models.CharField(max_length=3, verbose_name='Статус уведомления')),
                ('date_update', models.DateTimeField(verbose_name='Дата ввода')),
                ('patient_id', models.IntegerField()),
            ],
            options={
                'db_table': 'medexam_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('patient', models.TextField(verbose_name='Пациент')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('date_birthday', models.DateField(verbose_name='День рождения')),
                ('phone_home', models.CharField(max_length=10, verbose_name='Домашний телефон')),
                ('phone_mobile', models.CharField(max_length=13, verbose_name='Мобильный телефон')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('place_of_work', models.TextField(verbose_name='Место работы')),
                ('reference_number', models.CharField(max_length=30, verbose_name='Номер л-го удостверения')),
                ('addr_locality', models.CharField(max_length=3, verbose_name='Тип населенного пункта')),
                ('addr_city', models.CharField(max_length=100, verbose_name='Город')),
                ('addr_street', models.TextField(verbose_name='Улица')),
                ('addr_house', models.CharField(max_length=5, verbose_name='Дом')),
                ('addr_corpus', models.CharField(max_length=5, verbose_name='Корпус')),
                ('addr_room', models.CharField(max_length=5, verbose_name='Квартира')),
                ('addr_index', models.CharField(max_length=5, verbose_name='Индекс')),
                ('rajons', models.CharField(max_length=200, verbose_name='Район')),
                ('regions', models.CharField(max_length=200, verbose_name='Область')),
                ('mm', models.TextField(verbose_name='Медосмотры')),
                ('date_update', models.DateTimeField(verbose_name='Дата ввода')),
            ],
            options={
                'db_table': 'patient_list',
                'ordering': ['patient'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupRajon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rajons', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ('Районы',),
                'verbose_name_plural': 'Районы',
                'db_table': 'lookup_rajon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookupRegion',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('regions', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ('Регионы',),
                'verbose_name_plural': 'Регионы',
                'db_table': 'lookup_region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(db_column='last_name', max_length=100, verbose_name='Имя')),
                ('patron_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('inn', models.CharField(error_messages={'required': 'Please provide your inn.', 'unique': 'An account with this inn exist.'}, max_length=10, unique=True, verbose_name='ИНН')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('phone_home', models.CharField(max_length=10, verbose_name='Домашний телефон')),
                ('phone_mobile', models.CharField(max_length=13, verbose_name='Мобильный телефон')),
                ('email', models.CharField(error_messages={'required': 'Please provide your email address.', 'unique': 'An account with this email exist.'}, max_length=250, unique=True, verbose_name='Почта')),
                ('place_of_work', models.TextField(blank=True, db_column='place_of_work', null=True, verbose_name='Место работы')),
                ('reference_number', models.CharField(max_length=30, null=True, verbose_name='Номер л-го удостверения')),
                ('addr_locality', models.CharField(blank=True, choices=[('м', 'місто'), ('с', 'село'), ('смт', 'селище міського типу')], default='с', help_text='Введите тип населенного пункта', max_length=3, verbose_name='Тип населенного пункта')),
                ('addr_city', models.CharField(max_length=100, verbose_name='Город')),
                ('addr_abbreavation', models.CharField(blank=True, choices=[('бульвар', 'бульвар'), ('вул', 'вулиця'), ('кв', 'квартал'), ('пр-к', 'провулок'), ('пр', 'проспект'), ('тупік', 'тупік'), ('узвіз', 'узвіз'), ('шосе', 'шосе')], default='вул', help_text='Введите абривиатуру улицы', max_length=10, verbose_name='Тип(улица, бульвар...)')),
                ('addr_street', models.CharField(max_length=200, verbose_name='Улица')),
                ('addr_house', models.CharField(max_length=5, verbose_name='Дом')),
                ('addr_corpus', models.CharField(default=0, max_length=5, verbose_name='Корпус')),
                ('addr_room', models.CharField(default=0, max_length=5, verbose_name='Квартира')),
                ('addr_index', models.CharField(max_length=5, verbose_name='Индекс')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('rajon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cards.LookupRajon', verbose_name='Район')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cards.LookupRegion', verbose_name='Область')),
            ],
            options={
                'verbose_name': ('Пациент',),
                'verbose_name_plural': 'Пациент',
                'db_table': 'patient',
                'ordering': ['first_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_medical_examination', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата медосмотра')),
                ('purpose_medical_examination', models.CharField(blank=True, choices=[('Огляд водія', 'Огляд водія'), ('Дозвіл на зброю', 'Дозвіл на зброю'), ('Санітарна книжка', 'Санітарна книжка'), ('Сертифікат нарколога', 'Сертифікат нарколога'), ('Сертифікат психіатора', 'Сертифікат психіатора'), ('Довідка в бесейн', 'Довідка в бесейн'), ('Форма 086', 'Форма 086'), ('Інші', 'Інші')], default='Огляд водія', help_text='Введите цель медосмотра', max_length=20, verbose_name='Цель')),
                ('patient_status', models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', help_text='Введите статус уведомления', max_length=3, verbose_name='Статус')),
                ('dat_end', models.DateField(default=datetime.datetime(2021, 8, 13, 3, 37, 35, 728209), verbose_name='Дата действия справки')),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cards.Patient')),
            ],
            options={
                'verbose_name': ('Медосмотры',),
                'verbose_name_plural': 'Медосмотры',
                'db_table': 'medexamination',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lookuprajon',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_cards.LookupRegion'),
        ),
    ]
